spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/melog
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create #when to execute application drop table and recreate it
    properties:
      hibernate:
        #        show_sql: true   #write hibernate implementation SQL at System.out
        format_sql: true

logging.level:
  org.hibernate.SQL: debug #write hibernate implementation SQL through logger

jwt:
  secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff